"use client";

import React from "react";
import Link from "next/link";

export default function PublishingOverviewPage() {
  return (
    <div>
      <div style={{ marginBottom: "28px" }}>
        <h1 style={{ fontSize: "1.75rem", fontWeight: 700, letterSpacing: "-0.02em" }}>CMS Syndication & Publishing</h1>
        <p style={{ color: "var(--text-muted)", fontSize: "0.9rem", marginTop: "4px" }}>
          Seamless delivery to external Content Management Systems with strict human editorial sign-off.
        </p>
      </div>

      {/* Human Review Safeguard Callout */}
      <div
        className="glass-panel"
        style={{
          padding: "24px",
          marginBottom: "32px",
          borderLeft: "4px solid var(--accent-success)",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          flexWrap: "wrap",
          gap: "16px",
        }}
      >
        <div>
          <div style={{ fontSize: "0.8rem", textTransform: "uppercase", color: "var(--accent-success)", fontWeight: 700 }}>
            Mandatory Human Review Safeguard
          </div>
          <h3 style={{ fontSize: "1.2rem", fontWeight: 700, marginTop: "4px" }}>
            Zero Autonomous Over-Publishing
          </h3>
          <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginTop: "4px", maxWidth: "700px" }}>
            By default, all articles generated by the autonomous 11-agent pipeline transition to <strong>IN_REVIEW</strong>.
            Publishing to live production CMS environments strictly requires an Editor or Admin to review, approve,
            and authorize syndication.
          </p>
        </div>
      </div>

      {/* Platforms Grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))", gap: "20px" }}>
        {/* WordPress Card */}
        <div className="card">
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "12px" }}>
            <h3 style={{ fontSize: "1.2rem", fontWeight: 700 }}>WordPress</h3>
            <span className="badge badge-success">● Connected & Operational</span>
          </div>
          <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginBottom: "16px" }}>
            Full REST API v2 integration supporting direct draft generation, scheduling, and post publishing with category & tag mapping.
          </p>
          <div style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginBottom: "16px" }}>
            <div><strong>Protocol:</strong> REST API v2 (Application Passwords)</div>
            <div><strong>SSRF Protection:</strong> Active on site URL destinations</div>
          </div>
          <Link href="/articles" className="btn btn-secondary" style={{ width: "100%", textAlign: "center" }}>
            Publish from Article Workspace →
          </Link>
        </div>

        {/* Ghost Card */}
        <div className="card">
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "12px" }}>
            <h3 style={{ fontSize: "1.2rem", fontWeight: 700 }}>Ghost CMS</h3>
            <span className="badge" style={{ background: "var(--bg-secondary)", color: "var(--text-muted)" }}>
              ○ Provider Ready
            </span>
          </div>
          <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginBottom: "16px" }}>
            Standard Ghost Admin API adapter architecture ready for server-side webhook and key configuration.
          </p>
          <div style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginBottom: "16px" }}>
            <div><strong>Protocol:</strong> Ghost Admin API / JWT</div>
            <div><strong>Status:</strong> Extensible Provider Adapter</div>
          </div>
          <button disabled className="btn btn-secondary" style={{ width: "100%", opacity: 0.6 }}>
            Ready for Token Setup
          </button>
        </div>

        {/* Webflow Card */}
        <div className="card">
          <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: "12px" }}>
            <h3 style={{ fontSize: "1.2rem", fontWeight: 700 }}>Webflow</h3>
            <span className="badge" style={{ background: "var(--bg-secondary)", color: "var(--text-muted)" }}>
              ○ Provider Ready
            </span>
          </div>
          <p style={{ fontSize: "0.85rem", color: "var(--text-secondary)", marginBottom: "16px" }}>
            Webflow CMS API v2 schema collections integration ready for multi-site deployments.
          </p>
          <div style={{ fontSize: "0.8rem", color: "var(--text-muted)", marginBottom: "16px" }}>
            <div><strong>Protocol:</strong> Webflow REST API v2</div>
            <div><strong>Status:</strong> Extensible Provider Adapter</div>
          </div>
          <button disabled className="btn btn-secondary" style={{ width: "100%", opacity: 0.6 }}>
            Ready for Token Setup
          </button>
        </div>
      </div>
    </div>
  );
}
